openapi: "3.0.3"
info:
  title: "smtss API"
  description: "smtss API"
  version: "1.0.0"
servers:
- url: "https://smtss"
paths:
  /api/v1/samhandler/emottak/{samhandlerFnr}:
    get:
      description: ""
      parameters:
      - name: "samhandlerFnr"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Missing samhandlerFnr"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "tssid"
  /api/v1/samhandler/infotrygd/{samhandlerFnr}:
    get:
      description: ""
      parameters:
      - name: "samhandlerFnr"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Missing samhandlerFnr"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "tssid"
  /internal/is_alive:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "I'm alive! :)"
        "500":
          description: "Internal Server Error"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "I'm dead x_x"
  /internal/is_ready:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "I'm ready! :)"
        "500":
          description: "Internal Server Error"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Please wait! I'm not ready :("
  /internal/prometheus:
    get:
      description: ""
      parameters:
      - name: "name[]"
        in: "query"
        required: false
        schema:
          type: "string"