apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smtss
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmottak
    outbound:
      external:
        - host: b27apvl221.preprod.local
          ports:
            - name: mq
              port: 1413
              protocol: TCP
  envFrom:
    - secret: smtss-secrets
    - secret: smtss-keystore-pwd
  filesFrom:
    - mountPath: /var/run/keystore
      secret: smtss-keystore
  env:
    - name: MQ_HOST_NAME
      value: b27apvl221.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQLS03
    - name: MQ_CHANNEL_NAME
      value: Q1_SMTSS
    - name: MQ_TSS_SAMHANDLER_SERVICE_QUEUE
      value: QA.Q1_415.AS10_SAMHANDLER_SERVICE
    - name: MQ_KEYSTORE_PATH
      value: /var/run/keystore/smtss-keystore.jks