apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamsykmelding
  name: smtss-redis
  namespace: teamsykmelding
  annotations:
    nais.io/run-as-group: "0"
    nais.io/read-only-file-system: "false"
spec:
  image: bitnami/redis:latest
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 1Gi
  service:
    port: 6379
    protocol: redis
  accessPolicy:
    inbound:
      rules:
        - application: smtss
        - application: smtss-redisexporter
  envFrom:
    - secret: smtss-redis-password

---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamsykmelding
  name: smtss-redisexporter
  namespace: teamsykmelding
spec:
  image: oliver006/redis_exporter:latest
  port: 9121
  prometheus:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  liveness:
    path: /health
  accessPolicy:
    outbound:
      rules:
        - application: smtss-redis
  env:
    - name: REDIS_ADDR
      value: smtss-redis:6379
    - name: REDIS_EXPORTER_LOG_FORMAT
      value: json
  envFrom:
    - secret: smtss-redis-password