name: Deploy redis to dev
on:
  push:
    paths:
      - 'redis.yaml'
      - '.github/workflows/redis**'
    branches:
      - '*'
      - '!main'
jobs:
  deploy:
    name: Deploy Redis to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLUSTER: dev-gcp
          TEAM: teamsykmelding
          RESOURCE: redis.yaml
          PRINT_PAYLOAD: true